services:
  - type: web
    name: ffmodel-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python migration_startup.py"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1"
    healthCheckPath: "/api/health"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NETLIFY_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: TRUSTED_HOSTS
        value: "*"
      - key: RATE_LIMIT_REQUESTS
        value: "100"
      - key: RATE_LIMIT_WINDOW
        value: "60"
    pythonVersion: 3.11
    
  - type: redis
    name: ffmodel-redis
    plan: free
    
databases:
  - name: ffmodel-db
    plan: free 