services:
  - type: web
    name: ffmodel-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NETLIFY_URL
        sync: false
      - key: REDIS_URL
        sync: false
    pythonVersion: 3.11 